apiVersion: v1
kind: Secret
metadata:
    name: bws-secret
    labels:
        external-secrets.io/type: webhook
stringData:
    token: 0.cc73ced1-e86f-4e75-b134-b2060177b802.vj8akttoSZHtIqVwQUydWKMMchhTqh:Foxrbfy/hecz7nuy+cQ8nA==
    ORG_ID: c298a77c-31b5-4abc-a151-b16e006b39d5
