---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: esphome
  namespace: flux-system
spec:
  targetNamespace: home-automation
  dependsOn:
    - name: longhorn
  path: ./kubernetes/apps/home-automation/esphome/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
