---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-secret
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: /minio
