---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minio:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2025-03-12T18-04-18Z@sha256:46b3009bf7041eefbd90bd0d2b38c6ddc24d20a35d609551a1802c558c1c958f

            env:
              #MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}
              #MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
              #MINIO_PROMETHEUS_JOB_ID: minio
              #MINIO_PROMETHEUS_URL: https://prometheus.${SECRET_DOMAIN}
              #MINIO_PROMETHEUS_AUTH_TYPE: public
              #MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
              #MINIO_STORAGE_CLASS_RRS: EC:0
              #MINIO_STORAGE_CLASS_STANDARD: EC:0
              #MINIO_UPDATE: "off"
              MINIO_UPDATE: "off"
              MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
              MINIO_SERVER_URL: http://s3.${SECRET_DOMAIN}
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}
              MINIO_PROMETHEUS_AUTH_TYPE: public
            envFrom:
              - secretRef:
                  name: minio-secret
            args: ["server", "/data", "--console-address", ":9001"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false

            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              fsGroupChangePolicy: OnRootMismatch
              supplementalGroups: [100]

    service:
      minio:
        controller: minio
        ports:
          http:
            port: &port-console 9001
          api:
            port: &port-api 9000

    ingress:
      minio:
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Minio Console"
          hajimari.io/group: "storage"
          hajimari.io/icon: mdi:pail
          hajimari.io/instance: "admin"
        hosts:
          - host: &host-console "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: minio
                  port: *port-console

      s3:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-body-size: 5000m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
          hajimari.io/enable: "false"
        hosts:
          - host: &host-api "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: minio
                  port: *port-api

    persistence:
      config:
        existingClaim: minio-nfs
        globalMounts:
          - path: /data

    #persistence:
    #  config:
    #    type: nfs
    #    server: "${SECRET_TRUENAS_IP}"
    #    path: /mnt/DataPool/apps/minio
    #    globalMounts:
    #      - path: /data
