---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.20.24.243
    path: /mnt/DataPool/apps/minio
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 100Gi
