---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spoolman
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: spoolman-secret
    template:
      engineVersion: v2
      data:
        LOGIN: "{{ .LOGIN }}"
        PASSWORD: "{{ .PASSWORD }}"
  dataFrom:
  - extract:
      key: /spoolman
