---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app spoolman
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      spoolman:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
         config-permission-fix:
            image:
              repository: docker.io/library/busybox
              tag: latest
            command: [ "/bin/chown", "-R", "1000:1000", "/home/app/.local/share/spoolman/" ]
            securityContext:
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
        containers:
          app:
            image:
              repository: ghcr.io/donkie/spoolman
              tag: 0.21.0
            securityContext:
             runAsUser: 0
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 14m
                memory: 431M
              limits:
                memory: 431M
    service:
      app:
        controller: *app
        nameOverride: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 172.20.24.105
        ports:
          http:
            port: 8000

    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: spoolman.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
             - *app

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /home/app/.local/share/spoolman/
