---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akeyless-secret-store
spec:
  provider:
    akeyless:
      akeylessGWApiURL: https://api.akeyless.io
      authSecretRef:
        secretRef:
          accessID:
            key: accessId
            namespace: external-secrets
          accessType:
            key: accessType
            namespace: external-secrets
