---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: mosquitto-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .USERNAME }}"
        password: "{{ .PASSWORD }}"
        mosquitto_pwd: |
          {{ .USERNAME }}:{{ .PASSWORD }}
  dataFrom:
  - extract:
      key: /mqtt
