---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: "{{ .MOSQUITTO_MQTT_USERNAME }}"
        password: "{{ .MOSQUITTO_MQTT_PASSWORD }}"
        mosquitto_pwd: |-
          {{ .MOSQUITTO_MQTT_USERNAME }}:{{ .MOSQUITTO_MQTT_PASSWORD }}
  data:
    - secretKey: MOSQUITTO_MQTT_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 696b4b4a-200b-4b59-836d-b18c00b7ea56
        property: username
    - secretKey: MOSQUITTO_MQTT_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 696b4b4a-200b-4b59-836d-b18c00b7ea56
        property: password
