apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home-automation
stringData:
    username: mosquitto
    password: mosquitto
    mosquitto_pwd: |
      mosquitto:mosquitto
