# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8xZm5VoMHJna,iv:RIIqDQN19yaUn8oobKfEWOoafsEqYVIxiz6AupcoJkY=,tag:x4CioimZ2IgTY1NTXTENMQ==,type:str]
    password: ENC[AES256_GCM,data:N+UxcdZcWZ9c,iv:4oKq2fJknASBU6AugX92jWjIPBNmOMRx/7VactXaric=,tag:y/K5MMGJcf2trjxCrOntaQ==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:QgBxCelv+IyYpc+wQA9p2P+V0VY=,iv:6JjdVxy+amoWMeyJOP/qXNsKMxMYv4NjoCTkwLB19A8=,tag:+mIxBwWU2PTp6Fgz+cLUvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1964rmmj694glm395fgnu2ek4l256futzshj7xma6fm3cphdxeu4s2z6jv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS0dEeFhJY1dRVWFXRkhE
            Mko3eHVwMHhkS0tFZktqQUdwWURNTVNLUXpjCjFtNUJXYVdiL291L0dlZm1NQUtx
            eldVMGJ3MlBLQThyKytoNzFHWWJzVXcKLS0tIGZ5Yk1jcXVabUZIZlBrejdhaUdY
            eDFuRFpXWi9odk1paEpCK3hUVnA0a2sK6NgzdQhiWpD6a39eh5BFtmPAg00qi0k1
            WzPigRVwZtCfARuy9nMTFyEYXsLsnYb79bGPcfF7tQqTeLVLZraRjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T09:33:19Z"
    mac: ENC[AES256_GCM,data:t8adda3pHANGcOLspZB/HCm0o4vbS3G8g9pLJuGOaIcmJ1yFWHQNWw8inT059rvF4hy6+DgMqesM2klkQv2k4jQCuGCIUgkvUuDojOUPjO+RNsRnwItA9vZb2+0J3PnL8ChO/0QhHsMNI4vlm8Cq8hcA1CK+tsNBQyJR9UFawlk=,iv:WOWP9QuUAYcV8O/YRbPNOf/+zeNkTmAbbu2smkUxNGs=,tag:Ltuu3AFQo2F8l7MdtpOHHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
