apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:V/9rksBymCYT8+moLWosM8ypSovqOfjG/wA2COELAyKWjHDI,iv:ubAiwR1VjmO5kmQXGSfh/P49BjCFSt+pHMmxXuqY8TI=,tag:QADfclckMg7hny1udQk1uA==,type:str]
    credentials.json: ENC[AES256_GCM,data:KRaxuJdmBXFfjlz2CK3k7ZRyT6zwKPEZZFVBEO7EWTE6sHdZ99tbj1jKPc4LWskPK+IfuwPwnbx+bciEfL+u6CnGSeakm9jCQJ8D01vwWSSDhbyx2shr1mxgSFdrWY9lxxyKm0wDrGMq5ip7DD0IwGrD1o2b4GQu2v58f4dsdLlAZIQDs+72oaCXhnvjO/fcsKsW02Lq6JeLlldIA0NgT8tWTWVaafB/dH7HEihfgg==,iv:f/kac3AOVk3QNcrajj/dXdV4ggmh9wRHM8FgjvfoBfU=,tag:NEaRhUbkJQIiUkRhmZiGzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1964rmmj694glm395fgnu2ek4l256futzshj7xma6fm3cphdxeu4s2z6jv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WUJXeklyWnNNa0E1Z3Fr
            Q3p1bHZYSGc2MktHMDNzUFprVXdVL0wrTFVvCjJ1MDBRc0Z3TGlvalIvdWFNQndk
            OEFwditPUWpDWjdqL2xjL3hteVVyVG8KLS0tIHlyK3BXZlpYVkNoaVRTQVVpV2Fu
            Ny9relh1SFlBWUhmSUVCN2pmTEVZOGMKmpdEKlvywoNZATCEsA6n1zRVCw5hsxxm
            z/ySSd6Y5RaH1R7kidCX+GFM5p0I/nPGkjBTo268bGsMhg5z6R4KbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T09:50:16Z"
    mac: ENC[AES256_GCM,data:0SkLiYZEe5nUps/nBCPFCE3oZbgVkwSTNJ3wscCe+ew5wmrxr27RX8agigvSORoqFB2a3gDIp+bRZjzY7z4yWWXQuiLq7fJF6H0QqtidssmvQAws3FobCqhWFQp/Tci4jZsVm6zCMVBgGWNA/w6dKFM/9jKnH+PmTxBpiPRwWUM=,iv:Q7DaZ6IGIKlqWPtgtj9q5Pdk6ZGAkOtMPfZfOfRYHYk=,tag:yfnS5DJwlRst6euwDqPlCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
