---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obico
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: obico-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_APP_TOKEN: "{{ .PUSHOVER_APP_TOKEN }}"
  dataFrom:
    - extract:
        key: obico
