---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: network
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: truenas
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas
  namespace: network
  labels:
    kubernetes.io/service-name: truenas
addressType: IPv4
ports:
  - name: https
    appProtocol: https
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "172.20.24.243"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app truenas
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  #annotations:
     #external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
     #nginx.ingress.kubernetes.io/ssl-redirect: "true" # Redirects HTTP to HTTPS
     #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - truenas.${SECRET_DOMAIN}
  rules:
    - host: truenas.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 80

