---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hassactron
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: hassactron-secret
    template:
      engineVersion: v2
      data:
        options.json: |
          {
            "MQTTUser": "{{ .USERNAME }}",
            "MQTTPassword": "{{ .PASSWORD }}",
            "MQTTBroker": "mqtt.${SECRET_DOMAIN}",
            "Zones": [
              {
                "Name": "Bedrooms",
                "Id": 1
              },
              {
                "Name": "Living",
                "Id": 2
              }
            ],
            "RegisterZoneTemperatures": false
          }
  dataFrom:
  - extract:
      key: /mqtt
