---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hassactron
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      hassactron:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mikejmcguire/hass-actron-amd64
              tag: 2025.3.1
            env:
              TZ: Australia/Sydney
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 172.20.24.80
        ports:
          http:
            port: 80
            targetPort: 80

    persistence:
      data:
        enabled: true
        existingClaim: hassactron-data
        globalMounts:
          - path: /data
      options-secret:
        type: secret
        name: hassactron-secret
        globalMounts:
          - path: /data/options.json
            subPath: options.json
