---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: external-dns-unifi-secret
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_UNIFI_API: "{{ .EXTERNAL_DNS_UNIFI_API }}"
  dataFrom:
    - extract:
        key: external-dns-unifi
