---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kromgo/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./loki/ks.yaml
  - ./promtail/ks.yaml
  #- ./grafana/ks.yaml
