apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BkRAiWGGYCgI,iv:sE9m/bLj7GmxpF/OE5FVz7AAnn+2e590IUPKouQNqbo=,tag:MVGgAegZCP0AMRnbWGk+mg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ebfWnHRDMe5hrIeo+Q9u23rHeQ==,iv:mgo+VQhOjbIllDfMP63SNZ2hyi9I4yMxdGaqtrk3z3g=,tag:yJs9bJ200pjFIvbyhy3igQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:McVyVHzAoG9GvZF6fhmBR8PNPR9kE1u1V9/hY4EFVITR2Wk2,iv:pezmmkG9azrzNIpicetzPpaGsuJksw1CnAxBAsMCTXQ=,tag:IwOhq9YFFYOy5v/21A/GMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1964rmmj694glm395fgnu2ek4l256futzshj7xma6fm3cphdxeu4s2z6jv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRmFrYWE3WG5jLzVHOU8z
            d2tCSkpEVWQvVnNqdkM4Vm4vRWU0b0JGblRRCkhZajlFNnFJN2w4M1VhejVreFhD
            WitoWXZIRFU5Y0JGSTB0MTg4dkw4VDAKLS0tICthajdEeEhYRlFwdnByVk9rRE1x
            T2N3OWNDYndhYUhUOGF6Z3JNU1BvQ2sKXp7TYdLT0Q6osV43//35l/F+01KRbxCP
            Fu0PZGO+9sjQolzWS1NlhXwW/zvrUbgEmuohajeaQZSnjUfaq350lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T09:50:16Z"
    mac: ENC[AES256_GCM,data:KZy1PIyC2NEgvESBaZj901PYR4CZo8N82YDwFibn1djt5Eh0xRdZp328NcgdJbMvO+GtqFVEqqfbbHOQQg/InR4HlpB++M3pmDfcfGW/c6a1Kqfw5Zxmi4ZKUbibRcnL5E8pv+rn/DQif5Xt7GZg1yo0qMNAp+vq98xTcK6we2g=,iv:el3KvgMs1h/PFe5WkwgjVMM3tcCn6cKk8Y1imUwxEOQ=,tag:PfTclahNLYdqhTWiIp3Sjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
