# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pgadmin-secret
stringData:
  PGADMIN_DEFAULT_EMAIL: ryan.phelan@gmx.com
  PGADMIN_DEFAULT_PASSWORD: WfVObesTBpBHS1sTnV8t
  config_local.py: 8uLQoeJPhSCIqxR7kJdd

