apiVersion: v1
type: Opaque
metadata:
    name: pgadmin-secret
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:PuyHVFOVUbzcWdUlS2ZkLyHQAg==,iv:ZrsB2qdKaX87Fy4UOJCKh1qW9Az1Ze6UGUEff+jaJx8=,tag:NQdH1uNw9wy6NGfJzeaObQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:I9TDVP3/NRFMjfGA/Vi6afRWKyQ=,iv:k7noUpDCr9duq4XaveQ4222JnBa+km7pegsYuhOvd40=,tag:TPgckfi9AxBxLqprQ4mVzA==,type:str]
    config_local.py: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1964rmmj694glm395fgnu2ek4l256futzshj7xma6fm3cphdxeu4s2z6jv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla0cxY2JCbVJqSWVCZVBU
            aEMrMkQ3RTdIQ1ZBS240aWl5aEMrRlRaN0RvCnhqNTBrZGptWUVRSnRNTTdjSHll
            NG0rUWRGR1RVYWhKbkNiRDN3Vm5BQnMKLS0tIG5KU2RDd2NrNUJaT0dSQzgrWDZr
            ajgxS1BFU1AxN0lDRmlFaDQvTTBnNUEKJAqG/zKlpVI+5CFK1yPix1gWmbcSe7tQ
            oF38lyPAgpLVaNV4CfBrFstHBqGhysZuFHyKVha2if60NBgeEigo+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T02:06:50Z"
    mac: ENC[AES256_GCM,data:HEfQrvfSy1McbdaRLYDsgIJzBTV25Z0rrNFhLDNnDe5FJT6Hnu7v95gHc9QF4HEg0yskPbGXO/j/SRULP72sKgz5i0Z4PvG1H6RblV4Koqy0uYT4aVunAOSmuTBz2mZCoZ/vuLOE4olt+4DX7VcT8zdxPSexoNmp+UY8Tk5pQJM=,iv:RCYNs5uH8W4u0qH/IBrCf4xEcffCOfpqfC7bugQqAA0=,tag:uFgCewKT9CXBKsxevd0AaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
