---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: memos
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: memos-secret
    template:
      data:
        # App
        POSTGRES_URL: "postgres://{{ .MEMOS_POSTGRES_USER }}:{{ .MEMOS_POSTGRES_PASS }}@postgres16-rw.database/memos?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: memos
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local.
        INIT_POSTGRES_USER: "{{ .MEMOS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .MEMOS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /memos
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MEMOS_$1"
    - extract:
        key: /cloudnative-pg
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database-secrets
