---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      memos:
        annotations:
          reloader.stakater.com/auto: "true"
        #initContainers:
        #  init-db:
        #    image:
        #      repository: ghcr.io/home-operations/postgres-init
        #      tag: 16.4.0@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
        #      pullPolicy: Always
        #    envFrom:
        #      - secretRef:
        #          name: memos-secret
        containers:
          app:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.24.2
            env:
              TZ: ${TIMEZONE}
              MEMOS_PORT: "5230" # https://github.com/usememos/memos/issues/1782
              MEMOS_DRIVER: postgres
              MEMOS_DSN:
                valueFrom:
                  secretKeyRef:
                    name: memos-secret
                    key: POSTGRES_URL
              INIT_POSTGRES_DBNAME: memos
              INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local.
              INIT_POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: memos-secret
                    key: MEMOS_POSTGRES_USER
              INIT_POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: memos-secret
                    key: MEMOS_POSTGRES_PASS
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg
                    key: POSTGRES_SUPER_PASS
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 25m
                memory: 105M
              limits:
                memory: 105M
    service:
      app:
        controller: memos
        ports:
          http:
            port: 5230
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "memos.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /var/opt/memos
