---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.5.2@sha256:92594f14fd3cc0795c1934690aa7ea0bc99622edf0029df8a52a23e95ad3af2f
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 4000Mi
              limits:
                memory: 7000Mi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.100.2@sha256:0c31654f1125c3a685a42ed1f2946573f5ebaaf016c5bc0640c72f9f571267e0
            env:
              TZ: ${TIMEZONE}
            args:
              - "/config"
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"

    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: true
        runAsUser: 568 #1000
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: home-assistant
        nameOverride: home-assistant
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 172.20.24.100
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 8123
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
          sonos:
            enabled: true
            port: 1400
          emulated-hue:
            enabled: true
            port: 80
          upnp:
            enabled: true
            port: 1900
            protocol: UDP
            targetPort: 1900
          lifx:
            enabled: true
            port: 56700
      codeserver:
        type: ClusterIP
        controller: home-assistant
        ports:
          http:
            enabled: true
            port: 8080
            protocol: TCP
            targetPort: 8080
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host hass.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      codeserver:
        className: internal
        hosts:
          - host: &codeserverHost hass-code.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: codeserver
                  port: http
        tls:
          - hosts:
              - *codeserverHost
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            codeserver:
              - path: /config
      backups:
        type: nfs
        server: 172.20.24.243
        path: /mnt/DataPool/apps/homeassistant
        globalMounts:
          - path: /config/backups
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
