---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        #initContainers:
        #  init-db:
        #    envFrom: &envFrom
        #      - secretRef:
        #          name: home-assistant-secret
        #    image:
        #      repository: ghcr.io/onedr0p/postgres-init
        #      tag: 16.3
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.10.0
            env:
              TZ: ${TIMEZONE}
              POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
              POSTGRES_DB: home_assistant
              HASS_HTTP_TRUSTED_PROXY_1: 172.20.24.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.69.0.0/16
              HASS_HTTP_TRUSTED_PROXY_3: 10.96.0.0/16
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 41m
                memory: 552Mi
              limits:
                memory: 1Gi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.91.1@sha256:8403442d3472e411f72b6a5267b5ee0e62db27e258d81efebef40c3b41219970
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - "--port"
              - "12321"
              - /config
            resources:
              requests:
                cpu: 41m
                memory: 593Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 #568
        runAsGroup: 1000 #568
        fsGroup: 1000 #568
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: home-assistant
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 172.20.24.100
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 8123
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
          sonos:
            enabled: true
            port: 1400
          emulated-hue:
            enabled: true
            port: 80
          upnp:
            enabled: true
            port: 1900
            protocol: UDP
            targetPort: 1900
          lifx:
            enabled: true
            port: 56700
      codeserver:
        type: ClusterIP
        controller: home-assistant
        ports:
          http:
            enabled: true
            port: 12321
            protocol: TCP
            targetPort: 12321
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host hass.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      codeserver:
        className: internal
        hosts:
          - host: &codeserverHost hass-code.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: codeserver
                  port: http
        tls:
          - hosts:
              - *codeserverHost
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            codeserver:
              - path: /config
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
