apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: subnet-router
spec:
  hostname: k8s-subnet-router
  proxyClass: tailscale
  subnetRouter:
    advertiseRoutes:
      - "172.20.24.0/24"
      - "172.20.22.0/24"
