# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: tailscale
stringData:
    name: ENC[AES256_GCM,data:PbeWNyMLOMpXcPcHeSU=,iv:CAaDEKXJmoEgfqgE6l9kfM2jHu8MKHbEU5lMcDZssaA=,tag:qXc4tcFOboC3pUGQ30GzaQ==,type:str]
    template:
        engineVersion: ENC[AES256_GCM,data:rW4=,iv:oSmel7+Q7BQiirr3KaMzODuo5WOCSbP8y4ufh/fygig=,tag:HB2AKQDclwV37OIclkvx8A==,type:str]
        data:
            client_id: ENC[AES256_GCM,data:5dQs9fLxPK2iutPSWmAj5xI=,iv:uIytKPjsayC21S2plWGUUaO5UD7YdUOAdD8Sv7pZL5c=,tag:mfxJAzJCCAiQZluEKqvPIg==,type:str]
            client_secret: ENC[AES256_GCM,data:E0dRw5bbxrxu3QKVazQ+mSLm/CR2+FHm9hVYdyfDU3fTS9vDXVHlX4WfYAotZPVu4w39Wk0KVZd2npXWBZwBIg==,iv:o5RXe8rsmQ4KA3yszXeZ9QMgRlQF9TOeqeOky1CAWa8=,tag:K3HUhlPvFbC6DqWvYO8kAg==,type:str]
    tailscale_email: ENC[AES256_GCM,data:PLunbbZRJCRFOuScgVa3wiGWvA==,iv:2ghdNnqBM+grBzNBSuzaIx75hxYuki4p9CH+MB/mfT8=,tag:CZnsGZlrTy4T9YrFlJjp0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1964rmmj694glm395fgnu2ek4l256futzshj7xma6fm3cphdxeu4s2z6jv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWlPT0l1WVgzSGREUXVz
            M3RrclpCczVDU1QxdXphRFdyd0lDWkFEV20wClVybDE4dGVtc1F6a0IvQiswUU8r
            VHhGaFdxc0h2RWVvaThqSFJweE9qalkKLS0tIENMZzl5anA2dUxaVTJUdHJ2cmV4
            cnczWStoTkFtejFuRHBUU3pXOHNuTjAKXMKSTFLps/UTEpHl44dZiytL1JpSvCqK
            B5HozsxNJbXX4UxKidHA2r7aLqFDvLvtcEJwvLfK1CZ9QwjbyrRZ8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T04:08:19Z"
    mac: ENC[AES256_GCM,data:fvSLEOzpGe7ficgSIixBjjf/xhRVI/VfSAcodHzx/yHRL1hNJT2rvp7f8jD5xnkkglYS9QB3yXCDc5tSaoN9fBCiAMT99OHQYpJkHC2MsMpGMr0pE+n2ax/DdOB/uN+5nYiZREi6E9HcLOjT/fpxMY1awoTtkTUcuI48SOXcw/I=,iv:OuKJ8JA5Gq9srTy7U1o5WbuWz3l+wJf31ab+q35+orM=,tag:B7VcRxs0JZeTp0EGEt1iHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
