# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: tailscale-operator
    namespace: network
stringData:
    target: null
    template:
        data:
            values.yaml: ENC[AES256_GCM,data:8u/zQm01I1P04MJqBDQeQ22YzN/uSQjsE2/nynm82ply75RLgQYqA4VACC2FJmssc5hvAWXU+k4uOI9NmAowI7Ns/yt2dcrK50OnHPUtZVVZxJHhJXdhcnZJ+f6GOa9/gBlZ5xxJI99PDMPa/I4MWd3rY2TWoBBY,iv:EWPtpdg5HmnN8pUwKk0/3s0RrNWIVkQqgujGORhSTrg=,tag:ydfNGynt0X6ik++1vil7yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1964rmmj694glm395fgnu2ek4l256futzshj7xma6fm3cphdxeu4s2z6jv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcU1NOEdBTzZzc3hxZms0
            QnhERnprN1N0QVNlbVNlcFZLa3pESG9RY1RjCitHN3k3UDJzNXVtYVJzNDQ0SkhH
            STRobCtuVDF2US9UTHZmRkczYWxiY0EKLS0tIFcvMnJzSStFd0thQk05YWtRWkJV
            SnJRYStwK0JTaGVqSFFteWZzODZPbFkKjAVNcbYudsvxocn5mlH5Ozz7hUIcUE9j
            RrnX+/lYvsnExiLenqm9SgnGS31IpiYFmXBSnPMwlbEFyYik0O2DQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T04:16:24Z"
    mac: ENC[AES256_GCM,data:kay8Ono/YMuV6X8p4Y9keRP3BtOEM31fiIhE/XsE4SMbGebeBGOO2NJDHPUrMygMi4laP8z+hWALR5Yg/uZUTTb3AiwGVideDV1GrXywHxCsHY5PfM2JvWocKZ4XnH00jfEWf9VBJsiZNhp+nwIrdHC7SJ3R04wzdvNyhPNKGdg=,iv:Wm02U25ATakkmVRf+SMcZxfZL5/kqI5P/Tn/cFSxh3k=,tag:vxlOmthE3ui21AB0pTpeQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
