apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:FjKB6UttTZSoB1JYKSxFYqsJRjIL1u5IoV63oc8CHtk6RAFb1BJjzg==,iv:FvMQVFG/2LuqA35GU0u6GsF/8q+1e1oeCaIgVGeUGA8=,tag:bYsX4dzEXnB27DuhSOQwGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1964rmmj694glm395fgnu2ek4l256futzshj7xma6fm3cphdxeu4s2z6jv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MmRnT2wyU1R5R0toYy9r
            UHhBbmhIejVkZ1NCY3lnbmlDOEFRakUwcmxVCkFlczZyaUNZMTRUdExKdVo2ckZD
            clZESGJtOWJqNm10M3pEOVY0Q0paRmsKLS0tIHowRWZtRzB0L1ZOdXpsZUhwQ1hZ
            WXFFL2xBU3JuRnBCeENTNEJTV1pHR1EK9OGwBvWOL24DOWYgOfzLY6R/q0yvx/su
            7G4tNFULjZx4QwbuUVxhwRQMBPW12EeoBm8Xbzo3alRubp8HZZ67mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T09:50:16Z"
    mac: ENC[AES256_GCM,data:uEmEWvFzGk4gBOw1lUrhneTpseFR8UJGXKyP4ZnDclcRKdt56h2hYoPmru2736JlIuu0XQ6LLCpBjxZ4BuHZG4lMYN+/uiJ4hEMAGV4cKGwT7+V1Z/bXZ9+SIJ5BrfXtwGmnSJvXlfRBouTy7/2ShAOVstx51jRj8NYPau0QKf4=,iv:LPIoP3aSmpgb94uQ7KD+5tWQ+iMcnP/+eXhPuRivnmI=,tag:Xm0QJ0J/5pAIHe4uokpzTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
